### ISSUE TITLE
heasoftpy installation error

### ISSUE THREAD

**Issue by ghost** [HEASARC/heasoftpy#1]
I have successfully installed and initialized `HEAsoft`, and now I try to install `heasoftpy` in a Python environment,

I created the virtual environment using `conda` and then installed the dependencies in that environment, and used `python setup.py build` to get an error

```2022-06-26 12:04:10 -  INFO -      setup file found ...
/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
 warnings.warn(
running build
running build_py
2022-06-26 12:04:12 -  INFO - ------------------------------------------------------------
------------------------------------------------------------
2022-06-26 12:04:12 -  INFO - Starting heasoftpy installation ...
Starting heasoftpy installation ...
2022-06-26 12:04:12 -  INFO - ------------------------------
------------------------------
2022-06-26 12:04:12 -  INFO - Creating python wrappers ...
Creating python wrappers ...
2022-06-26 12:04:12 -  INFO - Installying python wrappers. There are 747 tasks!
Installying python wrappers. There are 747 tasks!
2022-06-26 12:04:12 -  INFO - .. 1/747 install uvottfc ...
.. 1/747 install uvottfc ...
2022-06-26 12:04:12 - ERROR - Failed in generating python wrappers
Failed in generating python wrappers
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    setup(
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 19, in run
    hspinstall._do_install()
  File "/home/jason/HEAsoft-6.30/heasoftpy/install.py", line 248, in _do_install
    _create_py_wrappers()
  File "/home/jason/HEAsoft-6.30/heasoftpy/install.py", line 67, in _create_py_wrappers
    generate_py_code()
  File "/home/jason/HEAsoft-6.30/heasoftpy/heasoftpy/utils.py", line 91, in generate_py_code
    hsp = HSPTask(task_name)
  File "/home/jason/HEAsoft-6.30/heasoftpy/heasoftpy/core.py", line 49, in __init__
    pfile  = HSPTask.find_pfile(name)
  File "/home/jason/HEAsoft-6.30/heasoftpy/heasoftpy/core.py", line 525, in find_pfile
    pfiles = re.split(';|:', os.environ['PFILES'])
  File "/home/jason/miniconda3/envs/heasoft/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'PFILES'```

**Comment by zoghbi-a** [comment]
Is heasoft initialized?  @mengjian2024 
It looks like the error is because the environment variable PFILES is not defined. This is usually defined when initializing heasoft with the script $HEADAS/headas-init.sh or $HEADAS/headas-init.csh

**Comment by ghost** [comment]
Yes, I initialized it @zoghbi-a 
I can use xspec,I want to use the python interface of heasofpy. Heasofpy is used in notebook, but I haven't configured it yet. The system I use is windows subsystem for Linux. I hope these messages I give will help you solve this complete problem. Thank you!

**Comment by zoghbi-a** [comment]
what do you get when doing `echo $PFILES` in the same terminal that runs xspec?

**Comment by ghost** [comment]
I input `echo $pfiles` in the same terminal running xspec to get
Jian » h                                                                         
(base) -----------------------------------------------------------------------------------------------------------------
Jian » echo $PFILES                                                               
/home/jian/pfiles;/home/jian/workdir/heasoft-6.30.1/x86_64-pc-linux-gnu-libc2.31/syspfiles
(base) -----------------------------------------------------------------------------------------------------------------

**Comment by zoghbi-a** [comment]
That is strange. The error occurs because the PFILES is not defined as an environment variable. One thing I can suggest, is to make sure the install script is run from the same terminal window where you did the `echo $PFILES` command. Does that give the same error?

**Comment by ghost** [comment]
Do you need to initialize heasoft first when the terminal executes `echo $PFILES`? I list the results after the terminal executes initialization and uninitialization respectively

uninitialized:
![image](https://user-images.githubusercontent.com/100666647/180024073-5aa8fc8b-d775-41b6-b0e2-6068b95ff062.png)
initialization:
![image](https://user-images.githubusercontent.com/100666647/180024434-eaf15a7c-9805-4610-86eb-eced92a0a53d.png)
Xspec terminal after initialization:
![image](https://user-images.githubusercontent.com/100666647/180024655-b58121b3-c420-4bda-8921-b04a4a09231d.png)

I hope this information can help you solve this problem. Thank you very much!

**Comment by zoghbi-a** [comment]
Thank you. Can you print back what you get by doing the following on the terminal (outside xspec). Please run in the folder that contains the `setup.py` of heasoftpy.
```shell
echo $PFILES
python setup.py build
```

**Comment by ghost** [comment]
Hello!
        I'm in the `setup.py` that contains heasoftpy run `python setup.py build`, the following errors appear
[err.txt](https://github.com/HEASARC/heasoftpy/files/9151907/err.txt) .

**Comment by ghost** [comment]
@zoghbi-a I used conda to create a virtual environment and successfully installed the heasoftpy module in this environment. Thank you very much for your help !
